layout_spectrum: 0.3972276
typography_spectrum: 0.1938114
color:
  saturation: 0.910616
  lightness: 0.7985083
  brandStrength: 0.6380989
  rhythmicContrast: 0.1319646
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Bakersfieldtattooremoval
